import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

// Output path: test vault during dev, current dir for production release
const outDir = prod
  ? "."
  : "C:/Users/Federico/Desktop/proyectos/personales/obsidian-test-vault/.obsidian/plugins/discord-export";

// Plugin that copies styles.css to the output directory after every build
const copyStylesPlugin = {
  name: "copy-styles",
  setup(build) {
    build.onEnd(() => {
      try {
        fs.copyFileSync("./styles.css", `${outDir}/styles.css`);
      } catch (e) {
        console.error("[copy-styles] Failed to copy styles.css:", e);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: `${outDir}/main.js`,
  plugins: [copyStylesPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
